apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: xfig
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xfig
    app.kubernetes.io/part-of: byoc-app-pqvt
  name: xfig
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: xfig
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: xfig
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-tytk-tenant/byoc-app-pqvt/xfig@sha256:1116cec5df0bcadbb6cb880f9d7039dbd57ed942344df2a15ae6c612f1add517
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
